config/routes.rb
SkiResorts::Application.routes.draw do
  resources :resorts

	

  root :to => 'resorts#index'

end

app/models/resort.rb
class Resort < ActiveRecord::Base
	reverse_geocoded_by :latitude, :longitude
	attr_accessible :name, :latitude, :longitude
	paginates_per 6
	
	def self.search(latitude='',longitude='')
		if latitude.to_f > 0 && longitude.to_f > 0
			return Resort.near([latitude,longitude] , 100, :order => :distance)
		end
		return Resort
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  # GET /resorts
  # GET /resorts.json
  def index
    
		latitude = params.has_key?(:latitude) && !params[:latitude].blank? ? params[:latitude] : ''
		longitude = params.has_key?(:longitude) && !params[:longitude].blank? ? params[:longitude] : ''
		
		resort_list = Resort.search(latitude, longitude)
		
		@resorts = resort_list.page params[:page]
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resorts }
    end
  end

  # GET /resorts/1
  # GET /resorts/1.json
  def show
    @resort = Resort.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resort }
    end
  end

  # GET /resorts/new
  # GET /resorts/new.json
  def new
    @resort = Resort.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resort }
    end
  end

  # GET /resorts/1/edit
  def edit
    @resort = Resort.find(params[:id])
  end

  # POST /resorts
  # POST /resorts.json
  def create
    @resort = Resort.new(params[:resort])

    respond_to do |format|
      if @resort.save
        format.html { redirect_to @resort, notice: 'Resort was successfully created.' }
        format.json { render json: @resort, status: :created, location: @resort }
      else
        format.html { render action: "new" }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resorts/1
  # PUT /resorts/1.json
  def update
    @resort = Resort.find(params[:id])

    respond_to do |format|
      if @resort.update_attributes(params[:resort])
        format.html { redirect_to @resort, notice: 'Resort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resorts/1
  # DELETE /resorts/1.json
  def destroy
    @resort = Resort.find(params[:id])
    @resort.destroy

    respond_to do |format|
      format.html { redirect_to resorts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ski Resorts" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
	</head>
  <body>
    <header class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<%= link_to 'Ski Resorts', root_path, :class=>"brand" %>
				<ul class="nav nav-pills">
					<li class="active">
						<%= link_to 'Home', resorts_path %>
					</li>
				</ul>
			</div>
		</header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
			<footer>
				<div class="container">
					<div class="row">
						<div class="span12">
							&nbsp;
						</div>
						<div class="span12">
							<p class="muted">&copy; Ski Resorts All Rights Reserved</p>
						</div>
					</div>
				</div>
			</footer>
    </div> <!--! end of #main -->
  </body>
</html>

app/views/resorts/_form.html.erb
<%= form_for(@resort) do |f| %>
  <% if @resort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resort.errors.count, "error") %> prohibited this resort from being saved:</h2>

      <ul>
      <% @resort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<div class="control-group">
    <%= f.label :name, :class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
	
	<div class="control-group">
    <%= f.label :latitude , :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :latitude %>
    </div>
  </div>
	
	<div class="control-group">
    <%= f.label :longitude, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :longitude %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit :class => "btn btn-primary"  %>
  </div>
<% end %>

app/views/resorts/edit.html.erb
<legend><h1 class="muted">Editing Resort</h1></legend>
<%= render 'form' %>

<%= link_to 'Show', @resort %> |
<%= link_to 'Back', resorts_path %>

app/views/resorts/index.html.erb
<h1 class="muted">Resorts</h1>
	<blockquote class="pull-right">
		<% if @resorts.length==0 %>
			<div class="alert alert-info">
				<button type="button" class="close" data-dismiss="alert">x</button>
				<strong>NOTE:</strong> Please enter both latitude and longitude to get the search results.
			</div>
		<% end %>
		<%= form_tag resorts_path, :method => 'get', :class => 'form-search' do %>  
      <label class="radio"> Latitude: </label>
        <%= text_field_tag :latitude, params[:latitude], :class=>'input-medium search-query', :placeholder=>'Enter Latitude' , :title => "e.g. 45.41010" %>  
			<label class="radio"> Longitude: </label>
				<%= text_field_tag :longitude, params[:longitude], :class=>'input-medium search-query' , :placeholder=>'Enter Longitude' , :title => "e.g. 6.60302" %>  
				<%= submit_tag 'Search', :name => nil, :class => "btn btn-primary" %>
				<%= link_to 'Clear Search', resorts_path , :class => "btn", :title => "Clear Search Result" %>
    <% end %>
		<small>Searching with latitude & longitude will give result list in ascending distance (i.e. nearest will come first)</small>
	</blockquote>

<table class="table table-striped table-bordered">
  <tr>
    <th>Resort</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th width="15%">Action</th>
  </tr>

<% @resorts.each do |resort| %>
  <tr>
    <td><%= resort.name %></td>
    <td><%= resort.latitude %></td>
    <td><%= resort.longitude %></td>
    <td>
			<div class="btn-group">
				<a class="btn" href="#"><i class="icon-action icon-white"></i> Action</a>
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><%= link_to '<i class="icon-pencil"></i> Edit'.html_safe, edit_resort_path(resort) %></li>
					<li><%= link_to '<i class="icon-trash"></i> Destroy'.html_safe, resort, confirm: 'Are you sure to delete this resort?', method: :delete %></li>
					<li><%= link_to '<i class="icon-eye-open"></i> Show'.html_safe, resort %></li>
				</ul>
			</div>
		</td>
  </tr>
<% end %>
</table>
<div class="pull-left">
	<%= paginate @resorts %>
</div>
<div class="pull-right">
	<br />
	<%= link_to 'New Resort', new_resort_path, :class=>"btn" , :title => "Create New Resort" %>
</div>

app/views/resorts/new.html.erb
<legend><h1 class="muted">New resort</h1></legend>
<%= render 'form' %>

<%= link_to 'Back', resorts_path %>

app/views/resorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resort.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @resort.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @resort.longitude %>
</p>


<%= link_to 'Edit', edit_resort_path(@resort) %> |
<%= link_to 'Back', resorts_path %>